name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: What would you like to see added or changed?
      placeholder: Clearly describe the feature.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use case
      description: Why is this feature important? How will it be used?
      placeholder: Explain the problem this feature solves.
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature for you?
      options:
        - Low
        - Medium
        - High
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
